version: '3.3'

services:
  db:
    image: mysql/mysql-server:5.7.37
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-root-password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: perception_wp
    depends_on:
      - db
    build:
      context: ./
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # # directories
      - ./src/:/var/www/html/wp-content/plugins/perception/
      # files
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
volumes:
  mysql_data:
